#-
# Copyright 2020 Kaiming Guo. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# .bash_profile - executed by the command interpreter for login shells.
#
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
#

# If running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi
if [ -d "$HOME/.local/share/man" ]; then
  MANPATH="$HOME/.local/share/man:$MANPATH"
fi

if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
  . /opt/local/etc/profile.d/bash_completion.sh
fi

# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab filetype=bash :
